export const videoMetadata = [{
  path: "/videos/pedro.mp4",
  username: "Guaxy das Estrelas",
  canPlaySound: false,
  loop: true,
  subStates: [],
  frequency: 0.3,
}, {
  path: "/videos/stark.mp4",
  username: "Tônio Stark",
  canPlaySound: false,
  loop: false,
  subStates: [],
  frequency: 0.3,
}, {
  path: "/videos/8gramas.mp4",
  username: "Dava Jonas",
  canPlaySound: true,
  loop: false,
  subStates: [],
  frequency: 0.4,
}, {
  path: "/videos/alanzoka.mp4",
  username: "Alanzoka",
  canPlaySound: true,
  loop: false,
  subStates: [],
  frequency: 0.2,
}, {
  path: "/videos/davy.mp4",
  username: "Davy Jones",
  canPlaySound: false,
  loop: true,
  subStates: [],
  frequency: 0.4,
}, {
  path: "/videos/chips.mp4",
  username: "Roberto Silva",
  canPlaySound: false,
  loop: true,
  subStates: [],
  frequency: 0.3,
}, {
  path: "/videos/bingchilling.mp4",
  username: "John Cena",
  canPlaySound: true,
  loop: false,
  subStates: [],
  frequency: 0.3,
}, {
  path: "/static/benstatic.png",
  username: "Ben Dog",
  canPlaySound: true,
  loop: false,
  subStates: ["/videos/hohoho.mp4", "/videos/yes.mp4", "/videos/no.mp4"],
  frequency: 0.3,
}, {
  path: "/videos/hamster.mp4",
  username: "Marcos Hamster",
  canPlaySound: true,
  loop: true,
  subStates: [],
  frequency: 0.3,
}, {
  path: "/static/antes.jpg",
  username: "Lurdes da Silva",
  canPlaySound: false,
  loop: false,
  subStates: [],
  frequency: 0.3,
}, {
  path: "/static/ltt.jpg",
  username: "Linus Sebastian",
  canPlaySound: false,
  loop: false,
  subStates: [],
  frequency: 0.3,
}, {
  path: "/static/staticReaction2.jpg",
  username: "André Alves",
  canPlaySound: false,
  loop: false,
  subStates: [],
  frequency: 0.3,
}, {
  path: "/static/staticReaction.jpg",
  username: "Marco das Correntes",
  canPlaySound: false,
  loop: false,
  subStates: [],
  frequency: 0.3,
}, {
  path: "/videos/porco.mp4",
  username: "Prof. Aurelio",
  canPlaySound: true,
  loop: false,
  subStates: [],
  frequency: 0.3,
}, {
  path: "/videos/chapolin.mp4",
  username: "Chapolin Colorado",
  canPlaySound: false,
  loop: false,
  subStates: [],
  frequency: 0.3,
}];